export enum Configuration {
  APP_PORT = "APP_PORT",
  APP_HOST = "APP_HOST",
  NODE_ENV = "NODE_ENV",
  DB_TYPE = "DB_TYPE",
  DB_HOST = "DB_HOST",
  DB_PORT = "DB_PORT",
  DB_NAME = "DB_NAME",
  DB_USERNAME = "DB_USERNAME",
  DB_PASSWORD = "DB_PASSWORD",
  JWT_ACCESS_SECRET = "JWT_ACCESS_SECRET",
  JWT_ACCESS_AGE_S = "JWT_ACCESS_AGE_S",
  JWT_REFRESH_SECRET = "JWT_REFRESH_SECRET",
  JWT_REFRESH_AGE_S = "JWT_REFRESH_AGE_S",
  REDIS_HOST = "REDIS_HOST",
  REDIS_PORT = "REDIS_PORT"
}
